// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    ChatsGroupsListData,
    ChatsGroupsListErrors,
    ChatsGroupsListResponses,
    ChatsListData,
    ChatsListErrors,
    ChatsListResponses,
    UsersAuthLoginCreateData,
    UsersAuthLoginCreateResponses,
    UsersAuthLogoutCreateData,
    UsersAuthLogoutCreateResponses,
    UsersAuthTokenRefreshCreateData,
    UsersAuthTokenRefreshCreateResponses,
    UsersAuthVerifyOtpCreateData,
    UsersAuthVerifyOtpCreateResponses,
    UsersEmailChangeCreateData,
    UsersEmailChangeCreateErrors,
    UsersEmailChangeCreateResponses,
    UsersEmailChangeVerifyCreateData,
    UsersEmailChangeVerifyCreateErrors,
    UsersEmailChangeVerifyCreateResponses,
    UsersPartialUpdateData,
    UsersPartialUpdateErrors,
    UsersPartialUpdateResponses,
    UsersPasswordResetCreateData,
    UsersPasswordResetCreateErrors,
    UsersPasswordResetCreateResponses,
    UsersPasswordResetVerifyCreateData,
    UsersPasswordResetVerifyCreateErrors,
    UsersPasswordResetVerifyCreateResponses,
    UsersPatientsListData,
    UsersPatientsListErrors,
    UsersPatientsListResponses,
    UsersRetrieveData,
    UsersRetrieveErrors,
    UsersRetrieveResponses,
} from "./types.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Список чатов пациента
 *
 * Возвращает плоский список чатов — только для пациентов.
 */
export const chatsList = <ThrowOnError extends boolean = false>(options?: Options<ChatsListData, ThrowOnError>) =>
    (options?.client ?? client).get<ChatsListResponses, ChatsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/",
        ...options,
    });

/**
 * Группы чатов доктора или опекуна
 *
 * Возвращает группы чатов по пациентам — только для докторов и опекунов.
 */
export const chatsGroupsList = <ThrowOnError extends boolean = false>(
    options?: Options<ChatsGroupsListData, ThrowOnError>
) =>
    (options?.client ?? client).get<ChatsGroupsListResponses, ChatsGroupsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/groups/",
        ...options,
    });

/**
 * Профиль пользователя
 *
 * Возвращает или обновляет профиль пользователя; доступен только владельцу аккаунта.
 */
export const usersRetrieve = <ThrowOnError extends boolean = false>(
    options: Options<UsersRetrieveData, ThrowOnError>
) =>
    (options.client ?? client).get<UsersRetrieveResponses, UsersRetrieveErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{user_id}/",
        ...options,
    });

/**
 * Обновление имени и фамилии
 *
 * Возвращает или обновляет профиль пользователя; доступен только владельцу аккаунта.
 */
export const usersPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPartialUpdateData, ThrowOnError>
) =>
    (options.client ?? client).patch<UsersPartialUpdateResponses, UsersPartialUpdateErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{user_id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Запрос смены email
 *
 * Проверяет новый email на уникальность и отправляет OTP для подтверждения.
 */
export const usersEmailChangeCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersEmailChangeCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersEmailChangeCreateResponses, UsersEmailChangeCreateErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{user_id}/email-change/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Подтверждение смены email
 *
 * Проверяет OTP и применяет новый email к аккаунту пользователя.
 */
export const usersEmailChangeVerifyCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersEmailChangeVerifyCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<
        UsersEmailChangeVerifyCreateResponses,
        UsersEmailChangeVerifyCreateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{user_id}/email-change/verify/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Запрос смены пароля
 *
 * Генерирует OTP и отправляет его на текущий email пользователя.
 */
export const usersPasswordResetCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPasswordResetCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersPasswordResetCreateResponses, UsersPasswordResetCreateErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{user_id}/password-reset/",
        ...options,
    });

/**
 * Подтверждение смены пароля
 *
 * Проверяет OTP и устанавливает новый пароль пользователя.
 */
export const usersPasswordResetVerifyCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPasswordResetVerifyCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<
        UsersPasswordResetVerifyCreateResponses,
        UsersPasswordResetVerifyCreateErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{user_id}/password-reset/verify/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Шаг 1 — вход по email и паролю
 *
 * Принимает email и пароль, отправляет OTP на почту, возвращает pre_auth_token.
 */
export const usersAuthLoginCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthLoginCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthLoginCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/login/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Выход из системы
 *
 * Добавляет refresh-токен в Redis-блэклист и завершает сессию.
 */
export const usersAuthLogoutCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthLogoutCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthLogoutCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/logout/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Обновление JWT-токенов
 *
 * Инвалидирует старый refresh-токен и выпускает новую пару.
 */
export const usersAuthTokenRefreshCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthTokenRefreshCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthTokenRefreshCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/token/refresh/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Шаг 2 — подтверждение OTP
 *
 * Принимает pre_auth_token и OTP, возвращает JWT access и refresh токены.
 */
export const usersAuthVerifyOtpCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthVerifyOtpCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthVerifyOtpCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/verify-otp/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Список пациентов
 *
 * Возвращает постраничный список пациентов с количеством опекунов для доктора или опекуна.
 */
export const usersPatientsList = <ThrowOnError extends boolean = false>(
    options?: Options<UsersPatientsListData, ThrowOnError>
) =>
    (options?.client ?? client).get<UsersPatientsListResponses, UsersPatientsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/patients/",
        ...options,
    });
