// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    ChatsCaregiverGroupsListData,
    ChatsCaregiverGroupsListErrors,
    ChatsCaregiverGroupsListResponses,
    ChatsDoctorGroupsListData,
    ChatsDoctorGroupsListErrors,
    ChatsDoctorGroupsListResponses,
    ChatsListData,
    ChatsListErrors,
    ChatsListResponses,
    ChatsMessagesDestroyData,
    ChatsMessagesDestroyErrors,
    ChatsMessagesDestroyResponses,
    ChatsMessagesEditPartialUpdateData,
    ChatsMessagesEditPartialUpdateErrors,
    ChatsMessagesEditPartialUpdateResponses,
    ChatsMessagesRetrieveData,
    ChatsMessagesRetrieveErrors,
    ChatsMessagesRetrieveResponses,
    DiagnosesAnalyticsRetrieveData,
    DiagnosesAnalyticsRetrieveErrors,
    DiagnosesAnalyticsRetrieveResponses,
    DiagnosesDiaryEntriesCreateData,
    DiagnosesDiaryEntriesCreateErrors,
    DiagnosesDiaryEntriesCreateResponses,
    DiagnosesDiaryEntriesDestroyData,
    DiagnosesDiaryEntriesDestroyErrors,
    DiagnosesDiaryEntriesDestroyResponses,
    DiagnosesDiaryEntriesListData,
    DiagnosesDiaryEntriesListErrors,
    DiagnosesDiaryEntriesListResponses,
    DiagnosesDiaryEntriesPartialUpdateData,
    DiagnosesDiaryEntriesPartialUpdateErrors,
    DiagnosesDiaryEntriesPartialUpdateResponses,
    DiagnosesDiaryFieldsListData,
    DiagnosesDiaryFieldsListErrors,
    DiagnosesDiaryFieldsListResponses,
    DiagnosesListData,
    DiagnosesListErrors,
    DiagnosesListResponses,
    NotificationsEmailSubscriptionCreateData,
    NotificationsEmailSubscriptionCreateResponses,
    NotificationsEmailSubscriptionDestroyData,
    NotificationsEmailSubscriptionDestroyResponses,
    NotificationsEmailSubscriptionRetrieveData,
    NotificationsEmailSubscriptionRetrieveResponses,
    NotificationsInAppReadAllCreateData,
    NotificationsInAppReadAllCreateResponses,
    NotificationsInAppReadPartialUpdateData,
    NotificationsInAppReadPartialUpdateErrors,
    NotificationsInAppReadPartialUpdateResponses,
    NotificationsInAppRetrieveData,
    NotificationsInAppRetrieveResponses,
    NotificationsPushSubscriptionCreateData,
    NotificationsPushSubscriptionCreateErrors,
    NotificationsPushSubscriptionCreateResponses,
    NotificationsPushSubscriptionDestroyData,
    NotificationsPushSubscriptionDestroyResponses,
    NotificationsSchedulesCreateData,
    NotificationsSchedulesCreateErrors,
    NotificationsSchedulesCreateResponses,
    NotificationsSchedulesListData,
    NotificationsSchedulesListErrors,
    NotificationsSchedulesListResponses,
    NotificationsSchedulesPartialUpdateData,
    NotificationsSchedulesPartialUpdateErrors,
    NotificationsSchedulesPartialUpdateResponses,
    NotificationsVapidPublicKeyRetrieveData,
    NotificationsVapidPublicKeyRetrieveResponses,
    UsersAuthLoginCreateData,
    UsersAuthLoginCreateResponses,
    UsersAuthLogoutCreateData,
    UsersAuthLogoutCreateResponses,
    UsersAuthTokenRefreshCreateData,
    UsersAuthTokenRefreshCreateResponses,
    UsersAuthVerifyOtpCreateData,
    UsersAuthVerifyOtpCreateResponses,
    UsersCaregiversListData,
    UsersCaregiversListResponses,
    UsersDoctorsListData,
    UsersDoctorsListResponses,
    UsersEmailChangeCreateData,
    UsersEmailChangeCreateErrors,
    UsersEmailChangeCreateResponses,
    UsersEmailChangeVerifyCreateData,
    UsersEmailChangeVerifyCreateErrors,
    UsersEmailChangeVerifyCreateResponses,
    UsersPartialUpdateData,
    UsersPartialUpdateErrors,
    UsersPartialUpdateResponses,
    UsersPasswordResetCreateData,
    UsersPasswordResetCreateErrors,
    UsersPasswordResetCreateResponses,
    UsersPasswordResetVerifyCreateData,
    UsersPasswordResetVerifyCreateErrors,
    UsersPasswordResetVerifyCreateResponses,
    UsersPatientsListData,
    UsersPatientsListErrors,
    UsersPatientsListResponses,
    UsersPatientsPartialUpdateData,
    UsersPatientsPartialUpdateErrors,
    UsersPatientsPartialUpdateResponses,
    UsersRetrieveData,
    UsersRetrieveErrors,
    UsersRetrieveResponses,
} from "./types.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Список чатов пациента
 *
 * Возвращает плоский список чатов — только для пациентов.
 */
export const chatsList = <ThrowOnError extends boolean = false>(options?: Options<ChatsListData, ThrowOnError>) =>
    (options?.client ?? client).get<ChatsListResponses, ChatsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/",
        ...options,
    });

/**
 * Список сообщений чата
 *
 * Возвращает страницу из 100 сообщений чата в порядке убывания id.
 */
export const chatsMessagesRetrieve = <ThrowOnError extends boolean = false>(
    options: Options<ChatsMessagesRetrieveData, ThrowOnError>
) =>
    (options.client ?? client).get<ChatsMessagesRetrieveResponses, ChatsMessagesRetrieveErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/{chatId}/messages/",
        ...options,
    });

/**
 * Удаление сообщения
 *
 * Помечает сообщение удалённым — только отправитель может удалить своё сообщение.
 */
export const chatsMessagesDestroy = <ThrowOnError extends boolean = false>(
    options: Options<ChatsMessagesDestroyData, ThrowOnError>
) =>
    (options.client ?? client).delete<ChatsMessagesDestroyResponses, ChatsMessagesDestroyErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/{chatId}/messages/{messageId}/",
        ...options,
    });

/**
 * Редактирование сообщения
 *
 * Обновляет текст сообщения — только отправитель может редактировать своё сообщение.
 */
export const chatsMessagesEditPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<ChatsMessagesEditPartialUpdateData, ThrowOnError>
) =>
    (options.client ?? client).patch<
        ChatsMessagesEditPartialUpdateResponses,
        ChatsMessagesEditPartialUpdateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/{chatId}/messages/{messageId}/edit/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Группы чатов опекуна
 *
 * Возвращает группы чатов по пациентам — только для опекунов.
 */
export const chatsCaregiverGroupsList = <ThrowOnError extends boolean = false>(
    options?: Options<ChatsCaregiverGroupsListData, ThrowOnError>
) =>
    (options?.client ?? client).get<ChatsCaregiverGroupsListResponses, ChatsCaregiverGroupsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/caregiver-groups/",
        ...options,
    });

/**
 * Группы чатов доктора
 *
 * Возвращает группы чатов по пациентам — только для докторов.
 */
export const chatsDoctorGroupsList = <ThrowOnError extends boolean = false>(
    options?: Options<ChatsDoctorGroupsListData, ThrowOnError>
) =>
    (options?.client ?? client).get<ChatsDoctorGroupsListResponses, ChatsDoctorGroupsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/chats/doctor-groups/",
        ...options,
    });

/**
 * Список диагнозов
 *
 * Возвращает все диагнозы системы для использования в фильтрах.
 */
export const diagnosesList = <ThrowOnError extends boolean = false>(
    options?: Options<DiagnosesListData, ThrowOnError>
) =>
    (options?.client ?? client).get<DiagnosesListResponses, DiagnosesListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/diagnoses/",
        ...options,
    });

/**
 * Аналитика дневниковых метрик пациента
 *
 * Возвращает числовые метрики пациента и точки данных за выбранный период.
 */
export const diagnosesAnalyticsRetrieve = <ThrowOnError extends boolean = false>(
    options?: Options<DiagnosesAnalyticsRetrieveData, ThrowOnError>
) =>
    (options?.client ?? client).get<
        DiagnosesAnalyticsRetrieveResponses,
        DiagnosesAnalyticsRetrieveErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/diagnoses/analytics/",
        ...options,
    });

/**
 * Список записей дневника
 *
 * Возвращает все записи дневника пациента в обратном хронологическом порядке.
 */
export const diagnosesDiaryEntriesList = <ThrowOnError extends boolean = false>(
    options?: Options<DiagnosesDiaryEntriesListData, ThrowOnError>
) =>
    (options?.client ?? client).get<DiagnosesDiaryEntriesListResponses, DiagnosesDiaryEntriesListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/diagnoses/diary-entries/",
        ...options,
    });

/**
 * Создание записи дневника
 *
 * Создаёт новую запись дневника с переданным набором значений метрик.
 */
export const diagnosesDiaryEntriesCreate = <ThrowOnError extends boolean = false>(
    options: Options<DiagnosesDiaryEntriesCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<
        DiagnosesDiaryEntriesCreateResponses,
        DiagnosesDiaryEntriesCreateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/diagnoses/diary-entries/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Удаление записи дневника
 *
 * Удаляет запись дневника вместе со всеми её значениями метрик.
 */
export const diagnosesDiaryEntriesDestroy = <ThrowOnError extends boolean = false>(
    options: Options<DiagnosesDiaryEntriesDestroyData, ThrowOnError>
) =>
    (options.client ?? client).delete<
        DiagnosesDiaryEntriesDestroyResponses,
        DiagnosesDiaryEntriesDestroyErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/diagnoses/diary-entries/{id}/",
        ...options,
    });

/**
 * Обновление записи дневника
 *
 * Заменяет значения метрик в существующей записи дневника через upsert.
 */
export const diagnosesDiaryEntriesPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<DiagnosesDiaryEntriesPartialUpdateData, ThrowOnError>
) =>
    (options.client ?? client).patch<
        DiagnosesDiaryEntriesPartialUpdateResponses,
        DiagnosesDiaryEntriesPartialUpdateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/diagnoses/diary-entries/{id}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Поля дневника для пациента
 *
 * Возвращает уникальные поля дневника, агрегированные по всем диагнозам пациента.
 */
export const diagnosesDiaryFieldsList = <ThrowOnError extends boolean = false>(
    options?: Options<DiagnosesDiaryFieldsListData, ThrowOnError>
) =>
    (options?.client ?? client).get<DiagnosesDiaryFieldsListResponses, DiagnosesDiaryFieldsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/diagnoses/diary-fields/",
        ...options,
    });

/**
 * Отключить email-уведомления
 *
 * Возвращает статус или меняет активность email-уведомлений; user_id позволяет управлять настройками пациента.
 */
export const notificationsEmailSubscriptionDestroy = <ThrowOnError extends boolean = false>(
    options?: Options<NotificationsEmailSubscriptionDestroyData, ThrowOnError>
) =>
    (options?.client ?? client).delete<NotificationsEmailSubscriptionDestroyResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/email-subscription/",
        ...options,
    });

/**
 * Статус email-уведомлений текущего пользователя
 *
 * Возвращает статус или меняет активность email-уведомлений; user_id позволяет управлять настройками пациента.
 */
export const notificationsEmailSubscriptionRetrieve = <ThrowOnError extends boolean = false>(
    options?: Options<NotificationsEmailSubscriptionRetrieveData, ThrowOnError>
) =>
    (options?.client ?? client).get<NotificationsEmailSubscriptionRetrieveResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/email-subscription/",
        ...options,
    });

/**
 * Включить email-уведомления
 *
 * Возвращает статус или меняет активность email-уведомлений; user_id позволяет управлять настройками пациента.
 */
export const notificationsEmailSubscriptionCreate = <ThrowOnError extends boolean = false>(
    options?: Options<NotificationsEmailSubscriptionCreateData, ThrowOnError>
) =>
    (options?.client ?? client).post<NotificationsEmailSubscriptionCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/email-subscription/",
        ...options,
    });

/**
 * Список in-app уведомлений текущего пользователя
 *
 * Возвращает пагинированный список in-app уведомлений с количеством непрочитанных.
 */
export const notificationsInAppRetrieve = <ThrowOnError extends boolean = false>(
    options?: Options<NotificationsInAppRetrieveData, ThrowOnError>
) =>
    (options?.client ?? client).get<NotificationsInAppRetrieveResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/in-app/",
        ...options,
    });

/**
 * Пометить in-app уведомление прочитанным
 *
 * Переводит одно in-app уведомление в статус «прочитано».
 */
export const notificationsInAppReadPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<NotificationsInAppReadPartialUpdateData, ThrowOnError>
) =>
    (options.client ?? client).patch<
        NotificationsInAppReadPartialUpdateResponses,
        NotificationsInAppReadPartialUpdateErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/in-app/{notificationId}/read/",
        ...options,
    });

/**
 * Пометить все in-app уведомления прочитанными
 *
 * Переводит все непрочитанные in-app уведомления пользователя в статус «прочитано».
 */
export const notificationsInAppReadAllCreate = <ThrowOnError extends boolean = false>(
    options?: Options<NotificationsInAppReadAllCreateData, ThrowOnError>
) =>
    (options?.client ?? client).post<NotificationsInAppReadAllCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/in-app/read-all/",
        ...options,
    });

/**
 * Отключить web push подписку
 *
 * Сохраняет push-подписку браузера или деактивирует её для текущего пользователя.
 */
export const notificationsPushSubscriptionDestroy = <ThrowOnError extends boolean = false>(
    options?: Options<NotificationsPushSubscriptionDestroyData, ThrowOnError>
) =>
    (options?.client ?? client).delete<NotificationsPushSubscriptionDestroyResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/push-subscription/",
        ...options,
    });

/**
 * Сохранить web push подписку
 *
 * Сохраняет push-подписку браузера или деактивирует её для текущего пользователя.
 */
export const notificationsPushSubscriptionCreate = <ThrowOnError extends boolean = false>(
    options: Options<NotificationsPushSubscriptionCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<
        NotificationsPushSubscriptionCreateResponses,
        NotificationsPushSubscriptionCreateErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/push-subscription/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Список расписаний уведомлений для пациента
 *
 * Возвращает расписания для пациента или создаёт расписание для текущего пользователя.
 */
export const notificationsSchedulesList = <ThrowOnError extends boolean = false>(
    options: Options<NotificationsSchedulesListData, ThrowOnError>
) =>
    (options.client ?? client).get<NotificationsSchedulesListResponses, NotificationsSchedulesListErrors, ThrowOnError>(
        {
            responseType: "json",
            security: [{ scheme: "bearer", type: "http" }],
            url: "/api/notifications/schedules/",
            ...options,
        }
    );

/**
 * Создать или обновить расписание уведомлений
 *
 * Возвращает расписания для пациента или создаёт расписание для текущего пользователя.
 */
export const notificationsSchedulesCreate = <ThrowOnError extends boolean = false>(
    options: Options<NotificationsSchedulesCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<
        NotificationsSchedulesCreateResponses,
        NotificationsSchedulesCreateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/schedules/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Обновить параметры расписания уведомлений
 *
 * Обновляет дни, время и статус активности расписания уведомлений.
 */
export const notificationsSchedulesPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<NotificationsSchedulesPartialUpdateData, ThrowOnError>
) =>
    (options.client ?? client).patch<
        NotificationsSchedulesPartialUpdateResponses,
        NotificationsSchedulesPartialUpdateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/notifications/schedules/{scheduleId}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Публичный VAPID-ключ для web push
 *
 * Возвращает публичный VAPID-ключ для создания push-подписки в браузере.
 */
export const notificationsVapidPublicKeyRetrieve = <ThrowOnError extends boolean = false>(
    options?: Options<NotificationsVapidPublicKeyRetrieveData, ThrowOnError>
) =>
    (options?.client ?? client).get<NotificationsVapidPublicKeyRetrieveResponses, unknown, ThrowOnError>({
        url: "/api/notifications/vapid-public-key/",
        ...options,
    });

/**
 * Профиль пользователя
 *
 * Возвращает или обновляет профиль пользователя; доступен только владельцу аккаунта.
 */
export const usersRetrieve = <ThrowOnError extends boolean = false>(
    options: Options<UsersRetrieveData, ThrowOnError>
) =>
    (options.client ?? client).get<UsersRetrieveResponses, UsersRetrieveErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{userId}/",
        ...options,
    });

/**
 * Обновление имени и фамилии
 *
 * Возвращает или обновляет профиль пользователя; доступен только владельцу аккаунта.
 */
export const usersPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPartialUpdateData, ThrowOnError>
) =>
    (options.client ?? client).patch<UsersPartialUpdateResponses, UsersPartialUpdateErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{userId}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Запрос смены email
 *
 * Проверяет новый email на уникальность и отправляет OTP для подтверждения.
 */
export const usersEmailChangeCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersEmailChangeCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersEmailChangeCreateResponses, UsersEmailChangeCreateErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{userId}/email-change/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Подтверждение смены email
 *
 * Проверяет OTP и применяет новый email к аккаунту пользователя.
 */
export const usersEmailChangeVerifyCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersEmailChangeVerifyCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<
        UsersEmailChangeVerifyCreateResponses,
        UsersEmailChangeVerifyCreateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{userId}/email-change/verify/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Запрос смены пароля
 *
 * Генерирует OTP и отправляет его на текущий email пользователя.
 */
export const usersPasswordResetCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPasswordResetCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersPasswordResetCreateResponses, UsersPasswordResetCreateErrors, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{userId}/password-reset/",
        ...options,
    });

/**
 * Подтверждение смены пароля
 *
 * Проверяет OTP и устанавливает новый пароль пользователя.
 */
export const usersPasswordResetVerifyCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPasswordResetVerifyCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<
        UsersPasswordResetVerifyCreateResponses,
        UsersPasswordResetVerifyCreateErrors,
        ThrowOnError
    >({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/{userId}/password-reset/verify/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Шаг 1. Вход по email и паролю
 *
 * Принимает email и пароль, отправляет OTP на почту, возвращает pre_auth_token.
 */
export const usersAuthLoginCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthLoginCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthLoginCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/login/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Выход из системы
 *
 * Добавляет refresh-токен в Redis-блэклист и завершает сессию.
 */
export const usersAuthLogoutCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthLogoutCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthLogoutCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/logout/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Обновление JWT-токенов
 *
 * Инвалидирует старый refresh-токен и выпускает новую пару.
 */
export const usersAuthTokenRefreshCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthTokenRefreshCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthTokenRefreshCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/token/refresh/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Шаг 2. Подтверждение OTP
 *
 * Принимает pre_auth_token и OTP, возвращает JWT access и refresh токены.
 */
export const usersAuthVerifyOtpCreate = <ThrowOnError extends boolean = false>(
    options: Options<UsersAuthVerifyOtpCreateData, ThrowOnError>
) =>
    (options.client ?? client).post<UsersAuthVerifyOtpCreateResponses, unknown, ThrowOnError>({
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/auth/verify-otp/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });

/**
 * Список опекунов
 *
 * Возвращает всех опекунов системы для использования в фильтрах.
 */
export const usersCaregiversList = <ThrowOnError extends boolean = false>(
    options?: Options<UsersCaregiversListData, ThrowOnError>
) =>
    (options?.client ?? client).get<UsersCaregiversListResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/caregivers/",
        ...options,
    });

/**
 * Список докторов
 *
 * Возвращает всех докторов системы для использования в фильтрах.
 */
export const usersDoctorsList = <ThrowOnError extends boolean = false>(
    options?: Options<UsersDoctorsListData, ThrowOnError>
) =>
    (options?.client ?? client).get<UsersDoctorsListResponses, unknown, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/doctors/",
        ...options,
    });

/**
 * Список пациентов
 *
 * Возвращает постраничный список пациентов с количеством опекунов для доктора или опекуна.
 */
export const usersPatientsList = <ThrowOnError extends boolean = false>(
    options?: Options<UsersPatientsListData, ThrowOnError>
) =>
    (options?.client ?? client).get<UsersPatientsListResponses, UsersPatientsListErrors, ThrowOnError>({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/patients/",
        ...options,
    });

/**
 * Редактирование пациента доктором
 *
 * Обновляет диагнозы и список докторов пациента; доступно только прикреплённому доктору.
 */
export const usersPatientsPartialUpdate = <ThrowOnError extends boolean = false>(
    options: Options<UsersPatientsPartialUpdateData, ThrowOnError>
) =>
    (options.client ?? client).patch<
        UsersPatientsPartialUpdateResponses,
        UsersPatientsPartialUpdateErrors,
        ThrowOnError
    >({
        responseType: "json",
        security: [{ scheme: "bearer", type: "http" }],
        url: "/api/users/patients/{patientId}/",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
