// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: "http://127.0.0.1:8000" | (string & {});
};

/**
 * Сериализатор запроса на смену email: проверяет уникальность и отправляет OTP на новый адрес.
 */
export type EmailChangeRequest = {
    new_email: string;
};

/**
 * Сериализатор подтверждения смены email: проверяет OTP и применяет новый адрес.
 */
export type EmailChangeVerify = {
    otp: string;
};

/**
 * Сериализатор первого шага: проверяет пароль, отправляет OTP, возвращает pre_auth_token.
 */
export type Login = {
    email: string;
};

/**
 * Сериализатор выхода из системы: добавляет refresh-токен в Redis-блэклист.
 */
export type Logout = {
    refresh: string;
};

/**
 * Сериализатор подтверждения смены пароля: проверяет OTP и устанавливает новый пароль.
 */
export type PasswordResetVerify = {
    otp: string;
};

/**
 * Сериализатор обновления имени и фамилии пользователя.
 */
export type PatchedUpdateProfile = {
    /**
     * Имя
     */
    first_name?: string;
    /**
     * Фамилия
     */
    last_name?: string;
};

/**
 * * `doctor` - Доктор
 * * `patient` - Пациент
 * * `caregiver` - Опекун
 */
export type RoleEnum = "doctor" | "patient" | "caregiver";

/**
 * Сериализатор ротации токенов: инвалидирует старый refresh, выпускает новую пару.
 */
export type TokenRefresh = {
    refresh: string;
};

/**
 * Сериализатор профиля пользователя для отображения публичных данных.
 */
export type UserProfile = {
    readonly id: number;
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
    /**
     * Роль
     */
    role: RoleEnum;
    /**
     * Дата регистрации
     */
    readonly date_joined: string;
};

/**
 * Сериализатор второго шага: проверяет OTP и выдаёт JWT-пару.
 */
export type VerifyOtp = {
    pre_auth_token: string;
    otp: string;
};

/**
 * Сериализатор первого шага: проверяет пароль, отправляет OTP, возвращает pre_auth_token.
 */
export type LoginWritable = {
    email: string;
    password: string;
};

/**
 * Сериализатор подтверждения смены пароля: проверяет OTP и устанавливает новый пароль.
 */
export type PasswordResetVerifyWritable = {
    otp: string;
    new_password: string;
};

/**
 * Сериализатор профиля пользователя для отображения публичных данных.
 */
export type UserProfileWritable = {
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
    /**
     * Роль
     */
    role: RoleEnum;
};

export type UsersRetrieveData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/";
};

export type UsersRetrieveErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type UsersRetrieveResponses = {
    200: UserProfile;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUpdateProfile;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/";
};

export type UsersPartialUpdateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type UsersPartialUpdateResponses = {
    200: UserProfile;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersEmailChangeCreateData = {
    body: EmailChangeRequest;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/email-change/";
};

export type UsersEmailChangeCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersEmailChangeCreateResponses = {
    /**
     * OTP отправлен на новый email
     */
    204: void;
};

export type UsersEmailChangeCreateResponse = UsersEmailChangeCreateResponses[keyof UsersEmailChangeCreateResponses];

export type UsersEmailChangeVerifyCreateData = {
    body: EmailChangeVerify;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/email-change/verify/";
};

export type UsersEmailChangeVerifyCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersEmailChangeVerifyCreateResponses = {
    200: UserProfile;
};

export type UsersEmailChangeVerifyCreateResponse =
    UsersEmailChangeVerifyCreateResponses[keyof UsersEmailChangeVerifyCreateResponses];

export type UsersPasswordResetCreateData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/password-reset/";
};

export type UsersPasswordResetCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersPasswordResetCreateResponses = {
    /**
     * OTP отправлен на email пользователя
     */
    204: void;
};

export type UsersPasswordResetCreateResponse =
    UsersPasswordResetCreateResponses[keyof UsersPasswordResetCreateResponses];

export type UsersPasswordResetVerifyCreateData = {
    body: PasswordResetVerifyWritable;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/password-reset/verify/";
};

export type UsersPasswordResetVerifyCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersPasswordResetVerifyCreateResponses = {
    /**
     * Пароль успешно изменён
     */
    204: void;
};

export type UsersPasswordResetVerifyCreateResponse =
    UsersPasswordResetVerifyCreateResponses[keyof UsersPasswordResetVerifyCreateResponses];

export type UsersAuthLoginCreateData = {
    body: LoginWritable;
    path?: never;
    query?: never;
    url: "/api/users/auth/login/";
};

export type UsersAuthLoginCreateResponses = {
    /**
     * pre_auth_token для второго шага
     */
    200: unknown;
};

export type UsersAuthLogoutCreateData = {
    body: Logout;
    path?: never;
    query?: never;
    url: "/api/users/auth/logout/";
};

export type UsersAuthLogoutCreateResponses = {
    /**
     * Успешный выход
     */
    204: void;
};

export type UsersAuthLogoutCreateResponse = UsersAuthLogoutCreateResponses[keyof UsersAuthLogoutCreateResponses];

export type UsersAuthTokenRefreshCreateData = {
    body: TokenRefresh;
    path?: never;
    query?: never;
    url: "/api/users/auth/token/refresh/";
};

export type UsersAuthTokenRefreshCreateResponses = {
    /**
     * Новые access и refresh токены
     */
    200: unknown;
};

export type UsersAuthVerifyOtpCreateData = {
    body: VerifyOtp;
    path?: never;
    query?: never;
    url: "/api/users/auth/verify-otp/";
};

export type UsersAuthVerifyOtpCreateResponses = {
    /**
     * access и refresh JWT-токены
     */
    200: unknown;
};
