// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: "http://127.0.0.1:8000" | (string & {});
};

/**
 * Группа чатов опекуна — один пациент, его доктора и другие опекуны.
 */
export type CaregiverChatGroup = {
    patient: ChatGroupMember;
    doctors: Array<ChatGroupMember>;
    caregivers: Array<ChatGroupMember>;
};

/**
 * Участник группы чатов с id чата, временем и превью последнего сообщения.
 */
export type ChatGroupMember = {
    id: number;
    first_name: string;
    last_name: string;
    chat_id: number | null;
    last_message_at: string | null;
    last_message: LastMessagePreview | null;
};

/**
 * Чат со сведениями о собеседнике — для плоского списка пациента.
 */
export type ChatItem = {
    readonly id: number;
    /**
     * Возвращает данные собеседника (не текущего пользователя).
     */
    readonly interlocutor: {
        [key: string]: unknown;
    };
    /**
     * Возвращает превью последнего сообщения из аннотаций запроса.
     */
    readonly last_message: {
        [key: string]: unknown;
    } | null;
    /**
     * Дата последнего сообщения
     */
    last_message_at?: string | null;
    /**
     * Дата создания
     */
    readonly created_at: string;
};

/**
 * Краткое представление диагноза для вложения в другие сериализаторы.
 */
export type DiagnosisShort = {
    readonly id: number;
    /**
     * Название
     */
    name: string;
    /**
     * Код (МКБ)
     */
    code: string;
};

/**
 * Группа чатов доктора — один пациент и все его опекуны.
 */
export type DoctorChatGroup = {
    patient: ChatGroupMember;
    caregivers: Array<ChatGroupMember>;
};

/**
 * Сериализатор запроса на смену email: проверяет уникальность и отправляет OTP на новый адрес.
 */
export type EmailChangeRequest = {
    new_email: string;
};

/**
 * Сериализатор подтверждения смены email: проверяет OTP и применяет новый адрес.
 */
export type EmailChangeVerify = {
    otp: string;
};

/**
 * Превью последнего сообщения для отображения в списке чатов.
 */
export type LastMessagePreview = {
    content: string;
    sender_name: string;
};

/**
 * Сериализатор первого шага: проверяет пароль, отправляет OTP, возвращает pre_auth_token.
 */
export type Login = {
    email: string;
};

/**
 * Сериализатор выхода из системы: добавляет refresh-токен в Redis-блэклист.
 */
export type Logout = {
    refresh: string;
};

/**
 * Сообщение чата с данными отправителя.
 */
export type Message = {
    readonly id: number;
    sender: MessageSender;
    /**
     * Скрывает текст удалённого сообщения.
     */
    readonly content: string | null;
    /**
     * Удалено
     */
    is_deleted?: boolean;
    readonly edited: boolean;
    /**
     * Дата отправки
     */
    readonly created_at: string;
};

/**
 * Страница сообщений с флагом наличия более старых записей.
 */
export type MessagePage = {
    results: Array<Message>;
    has_more: boolean;
};

/**
 * Краткие данные отправителя сообщения.
 */
export type MessageSender = {
    id: number;
    first_name: string;
    last_name: string;
};

/**
 * Сериализатор подтверждения смены пароля: проверяет OTP и устанавливает новый пароль.
 */
export type PasswordResetVerify = {
    otp: string;
};

/**
 * Сериализатор обновления имени и фамилии пользователя.
 */
export type PatchedUpdateProfile = {
    /**
     * Имя
     */
    first_name?: string;
    /**
     * Фамилия
     */
    last_name?: string;
};

/**
 * Опекун пациента с полями пользователя верхнего уровня для корректной генерации схемы.
 */
export type PatientCaregiver = {
    id: number;
    email: string;
    first_name: string;
    last_name: string;
};

/**
 * Диагноз пациента с полями диагноза верхнего уровня для корректной генерации схемы.
 */
export type PatientDiagnosis = {
    id: number;
    name: string;
    code: string;
};

/**
 * Доктор пациента с полями пользователя верхнего уровня для корректной генерации схемы.
 */
export type PatientDoctor = {
    id: number;
    email: string;
    first_name: string;
    last_name: string;
};

/**
 * Сериализатор элемента списка пациентов: основные поля, опекуны, доктора и диагнозы.
 */
export type PatientListItem = {
    readonly id: number;
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
    /**
     * Дата регистрации
     */
    readonly date_joined: string;
    caregiver_count: number;
    diagnoses: Array<PatientDiagnosis>;
    doctors: Array<PatientDoctor>;
    caregivers: Array<PatientCaregiver>;
};

export type PatientListResponse = {
    count: number;
    results: Array<PatientListItem>;
};

/**
 * * `doctor` - Доктор
 * * `patient` - Пациент
 * * `caregiver` - Опекун
 */
export type RoleEnum = "doctor" | "patient" | "caregiver";

/**
 * Сериализатор ротации токенов: инвалидирует старый refresh, выпускает новую пару.
 */
export type TokenRefresh = {
    refresh: string;
};

/**
 * Сериализатор профиля пользователя для отображения публичных данных.
 */
export type UserProfile = {
    readonly id: number;
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
    /**
     * Роль
     */
    role: RoleEnum;
    /**
     * Дата регистрации
     */
    readonly date_joined: string;
};

/**
 * Краткое представление пользователя для списков фильтрации.
 */
export type UserShort = {
    readonly id: number;
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
};

/**
 * Сериализатор второго шага: проверяет OTP и выдаёт JWT-пару.
 */
export type VerifyOtp = {
    pre_auth_token: string;
    otp: string;
};

/**
 * Чат со сведениями о собеседнике — для плоского списка пациента.
 */
export type ChatItemWritable = {
    /**
     * Дата последнего сообщения
     */
    last_message_at?: string | null;
};

/**
 * Краткое представление диагноза для вложения в другие сериализаторы.
 */
export type DiagnosisShortWritable = {
    /**
     * Название
     */
    name: string;
    /**
     * Код (МКБ)
     */
    code: string;
};

/**
 * Сериализатор первого шага: проверяет пароль, отправляет OTP, возвращает pre_auth_token.
 */
export type LoginWritable = {
    email: string;
    password: string;
};

/**
 * Сообщение чата с данными отправителя.
 */
export type MessageWritable = {
    /**
     * Удалено
     */
    is_deleted?: boolean;
};

/**
 * Страница сообщений с флагом наличия более старых записей.
 */
export type MessagePageWritable = {
    results: Array<MessageWritable>;
    has_more: boolean;
};

/**
 * Сериализатор подтверждения смены пароля: проверяет OTP и устанавливает новый пароль.
 */
export type PasswordResetVerifyWritable = {
    otp: string;
    new_password: string;
};

/**
 * Сериализатор элемента списка пациентов: основные поля, опекуны, доктора и диагнозы.
 */
export type PatientListItemWritable = {
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
    caregiver_count: number;
    diagnoses: Array<PatientDiagnosis>;
    doctors: Array<PatientDoctor>;
    caregivers: Array<PatientCaregiver>;
};

export type PatientListResponseWritable = {
    count: number;
    results: Array<PatientListItemWritable>;
};

/**
 * Сериализатор профиля пользователя для отображения публичных данных.
 */
export type UserProfileWritable = {
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
    /**
     * Роль
     */
    role: RoleEnum;
};

/**
 * Краткое представление пользователя для списков фильтрации.
 */
export type UserShortWritable = {
    email: string;
    /**
     * Имя
     */
    first_name: string;
    /**
     * Фамилия
     */
    last_name: string;
};

export type ChatsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/chats/";
};

export type ChatsListErrors = {
    /**
     * Доступ запрещён — только для пациентов
     */
    403: unknown;
};

export type ChatsListResponses = {
    200: Array<ChatItem>;
};

export type ChatsListResponse = ChatsListResponses[keyof ChatsListResponses];

export type ChatsMessagesRetrieveData = {
    body?: never;
    path: {
        chat_id: number;
    };
    query?: {
        /**
         * Загрузить сообщения старее указанного id (для скроллинга вверх)
         */
        before_id?: number;
    };
    url: "/api/chats/{chat_id}/messages/";
};

export type ChatsMessagesRetrieveErrors = {
    /**
     * Пользователь не является участником чата
     */
    403: unknown;
    /**
     * Чат не найден
     */
    404: unknown;
};

export type ChatsMessagesRetrieveResponses = {
    200: MessagePage;
};

export type ChatsMessagesRetrieveResponse = ChatsMessagesRetrieveResponses[keyof ChatsMessagesRetrieveResponses];

export type ChatsMessagesDestroyData = {
    body?: never;
    path: {
        chat_id: number;
        message_id: number;
    };
    query?: never;
    url: "/api/chats/{chat_id}/messages/{message_id}/";
};

export type ChatsMessagesDestroyErrors = {
    /**
     * Нельзя удалить чужое сообщение или нет доступа к чату
     */
    403: unknown;
    /**
     * Сообщение не найдено
     */
    404: unknown;
};

export type ChatsMessagesDestroyResponses = {
    /**
     * Сообщение удалено
     */
    204: void;
};

export type ChatsMessagesDestroyResponse = ChatsMessagesDestroyResponses[keyof ChatsMessagesDestroyResponses];

export type ChatsMessagesEditPartialUpdateData = {
    body?: {
        content: string;
    };
    path: {
        chat_id: number;
        message_id: number;
    };
    query?: never;
    url: "/api/chats/{chat_id}/messages/{message_id}/edit/";
};

export type ChatsMessagesEditPartialUpdateErrors = {
    /**
     * Нельзя редактировать чужое сообщение или нет доступа к чату
     */
    403: unknown;
    /**
     * Сообщение не найдено или удалено
     */
    404: unknown;
};

export type ChatsMessagesEditPartialUpdateResponses = {
    200: MessagePage;
};

export type ChatsMessagesEditPartialUpdateResponse =
    ChatsMessagesEditPartialUpdateResponses[keyof ChatsMessagesEditPartialUpdateResponses];

export type ChatsCaregiverGroupsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/chats/caregiver-groups/";
};

export type ChatsCaregiverGroupsListErrors = {
    /**
     * Доступ запрещён — только для опекунов
     */
    403: unknown;
};

export type ChatsCaregiverGroupsListResponses = {
    200: Array<CaregiverChatGroup>;
};

export type ChatsCaregiverGroupsListResponse =
    ChatsCaregiverGroupsListResponses[keyof ChatsCaregiverGroupsListResponses];

export type ChatsDoctorGroupsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/chats/doctor-groups/";
};

export type ChatsDoctorGroupsListErrors = {
    /**
     * Доступ запрещён — только для докторов
     */
    403: unknown;
};

export type ChatsDoctorGroupsListResponses = {
    200: Array<DoctorChatGroup>;
};

export type ChatsDoctorGroupsListResponse = ChatsDoctorGroupsListResponses[keyof ChatsDoctorGroupsListResponses];

export type DiagnosesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/diagnoses/";
};

export type DiagnosesListErrors = {
    /**
     * Доступ запрещён — только для докторов и опекунов
     */
    403: unknown;
};

export type DiagnosesListResponses = {
    200: Array<DiagnosisShort>;
};

export type DiagnosesListResponse = DiagnosesListResponses[keyof DiagnosesListResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/";
};

export type UsersRetrieveErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type UsersRetrieveResponses = {
    200: UserProfile;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUpdateProfile;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/";
};

export type UsersPartialUpdateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
    /**
     * Пользователь не найден
     */
    404: unknown;
};

export type UsersPartialUpdateResponses = {
    200: UserProfile;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersEmailChangeCreateData = {
    body: EmailChangeRequest;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/email-change/";
};

export type UsersEmailChangeCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersEmailChangeCreateResponses = {
    /**
     * OTP отправлен на новый email
     */
    204: void;
};

export type UsersEmailChangeCreateResponse = UsersEmailChangeCreateResponses[keyof UsersEmailChangeCreateResponses];

export type UsersEmailChangeVerifyCreateData = {
    body: EmailChangeVerify;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/email-change/verify/";
};

export type UsersEmailChangeVerifyCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersEmailChangeVerifyCreateResponses = {
    200: UserProfile;
};

export type UsersEmailChangeVerifyCreateResponse =
    UsersEmailChangeVerifyCreateResponses[keyof UsersEmailChangeVerifyCreateResponses];

export type UsersPasswordResetCreateData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/password-reset/";
};

export type UsersPasswordResetCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersPasswordResetCreateResponses = {
    /**
     * OTP отправлен на email пользователя
     */
    204: void;
};

export type UsersPasswordResetCreateResponse =
    UsersPasswordResetCreateResponses[keyof UsersPasswordResetCreateResponses];

export type UsersPasswordResetVerifyCreateData = {
    body: PasswordResetVerifyWritable;
    path: {
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}/password-reset/verify/";
};

export type UsersPasswordResetVerifyCreateErrors = {
    /**
     * Доступ запрещён
     */
    403: unknown;
};

export type UsersPasswordResetVerifyCreateResponses = {
    /**
     * Пароль успешно изменён
     */
    204: void;
};

export type UsersPasswordResetVerifyCreateResponse =
    UsersPasswordResetVerifyCreateResponses[keyof UsersPasswordResetVerifyCreateResponses];

export type UsersAuthLoginCreateData = {
    body: LoginWritable;
    path?: never;
    query?: never;
    url: "/api/users/auth/login/";
};

export type UsersAuthLoginCreateResponses = {
    /**
     * pre_auth_token для второго шага
     */
    200: unknown;
};

export type UsersAuthLogoutCreateData = {
    body: Logout;
    path?: never;
    query?: never;
    url: "/api/users/auth/logout/";
};

export type UsersAuthLogoutCreateResponses = {
    /**
     * Успешный выход
     */
    204: void;
};

export type UsersAuthLogoutCreateResponse = UsersAuthLogoutCreateResponses[keyof UsersAuthLogoutCreateResponses];

export type UsersAuthTokenRefreshCreateData = {
    body: TokenRefresh;
    path?: never;
    query?: never;
    url: "/api/users/auth/token/refresh/";
};

export type UsersAuthTokenRefreshCreateResponses = {
    /**
     * Новые access и refresh токены
     */
    200: unknown;
};

export type UsersAuthVerifyOtpCreateData = {
    body: VerifyOtp;
    path?: never;
    query?: never;
    url: "/api/users/auth/verify-otp/";
};

export type UsersAuthVerifyOtpCreateResponses = {
    /**
     * access и refresh JWT-токены
     */
    200: unknown;
};

export type UsersCaregiversListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/users/caregivers/";
};

export type UsersCaregiversListResponses = {
    200: Array<UserShort>;
};

export type UsersCaregiversListResponse = UsersCaregiversListResponses[keyof UsersCaregiversListResponses];

export type UsersDoctorsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/users/doctors/";
};

export type UsersDoctorsListResponses = {
    200: Array<UserShort>;
};

export type UsersDoctorsListResponse = UsersDoctorsListResponses[keyof UsersDoctorsListResponses];

export type UsersPatientsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Только прикреплённые к текущему доктору пациенты. Для опекунов игнорируется.
         */
        attached?: boolean;
        /**
         * Фильтр по опекунам (повторяемый параметр): пациенты хотя бы одного из указанных опекунов.
         */
        caregivers?: Array<number>;
        /**
         * Фильтр по диагнозам (повторяемый параметр): пациенты хотя бы с одним из указанных диагнозов.
         */
        diagnoses?: Array<number>;
        /**
         * Фильтр по докторам (повторяемый параметр): пациенты хотя бы одного из указанных докторов.
         */
        doctors?: Array<number>;
        /**
         * Фильтр по наличию опекуна: all — все, yes — есть опекун, no — нет опекуна.
         */
        has_caregiver?: "all" | "no" | "yes";
        /**
         * Номер страницы (начиная с 1).
         */
        page?: number;
        /**
         * Количество записей на странице.
         */
        page_size?: number;
        /**
         * Поиск по имени, фамилии или email пациента (регистронезависимый).
         */
        search?: string;
    };
    url: "/api/users/patients/";
};

export type UsersPatientsListErrors = {
    /**
     * Доступ запрещён — только для докторов и опекунов
     */
    403: unknown;
};

export type UsersPatientsListResponses = {
    200: PatientListResponse;
};

export type UsersPatientsListResponse = UsersPatientsListResponses[keyof UsersPatientsListResponses];
